[package]
name = "comet-eventbus"
version = "0.1.0"
edition = "2021"

[dependencies]
anymap = "0.12"
async-trait = "0.1"
futures = "0.3"
hex = "0.4"
rand = "0.8"
tokio = { version = "1.20", default-features = false, features = ["rt", "sync"] }

[dev-dependencies]
tokio = { version = "1.20", features = ["macros", "rt-multi-thread"] }